default: &default
  host: <%= ENV.fetch("REDIS_DEV_HOST", "localhost") %>
  port: 6379
  db: 0
  password: <%= ENV.fetch("REDIS_DEV_PASSWORD", nil) %>

development:
  <<: *default

test:
  <<: *default
  db: 1

production:
  <<: *default
  host: <%= ENV.fetch("REDIS_HOST", "localhost") %>
  db: 2
  password: <%= ENV.fetch("REDIS_PASSWORD", nil) %>